feat(DEX-4079,DEX-4167): hide-unhide sidebar, location flag on section and sequence and some hotfixes.
wgu-opensource/openedx-mfe-learning pull request #33
Opened 2023-09-27 21:40 UTC by AngelRicardezWGU

# Overview

This PR includes: 

Hide and Unhide vertical sidebar, design team still trying things so this is some kind of alpha so they can try it and see how it looks. 

Current page location flag on section and sequence when is collapsed. 

Some hot fixes.

## Checklist

⚠️ **Please make sure to fill this checklist before asking for reviews.**

- [ ] Code is correctly formatted and linted
- [ ] Unit tests are updated and are passing
- [ ] PR title follows [conventional commits](https://www.conventionalcommits.org/en/v1.0.0/#summary):
      i.e. `feat(CUR-###): Feature title`
- [ ] PR Title aligns to Semantic-Release [supported prefixes](https://www.conventionalcommits.org/en/v1.0.0/#examples) (NOTE: prefixes are case sensitive, keep lower-case):

```diff
 feat() - Feature (0.X.0)
 fix() - Patch (0.0.X)
 docs() - Patch (0.0.X), will only scope to README changes
 refactor() - Patch (0.0.X)
 revert() - Patch (0.0.X)
 style() - Patch (0.0.X)
```

- [ ] Check for unused files
- [ ] Check work before asking for reviewers
- [ ] Fix any linting errors
- [ ] SECURITY: No secrets where commited to the repo
- [ ] COMPLIANCE: Commited code is not propietary and adheres to Open Source licensing

2023-09-27 21:51 UTC, rodmgwgu requested changes

2023-09-27 21:51 UTC, rodmgwgu commented on src/components/Sequence/Sequence.jsx
> +    <button data-testid={`sequence-button-${id}`} type="button" className={classNames('sidebar-item-header', { active: isActiveSequence, 'has-current-unit': hasCurrentUnit && collapsibleMenuState[sec
Is this code formatted? looks too long for one line

2023-09-27 22:30 UTC, keoniWGU submitted a review, later dismissed

2023-09-27 22:41 UTC, rodmgwgu approved these changes

2023-09-28 02:12 UTC, keoniWGU approved these changes

2023-09-28 02:39 UTC, merged